export {
  fetchStaffOrders,
  fetchWaiterOrders,
  updateOrderStatus,
  markOrderPaid,
  fetchProducts,
  fetchCategories,
  addOrderItems,
  createOrder,
  fetchTables,
  fetchHalls,
  updateTableStatus,
  fetchOrderById,
  updateOrderItemStatus,
  updateOrderItem,
  removeOrderItem,
} from './waiter-api';
