export {
  fetchStaffOrders,
  fetchWaiterOrders,
  updateOrderStatus,
  markOrderPaid,
  fetchProducts,
  fetchCategories,
  addOrderItems,
  createOrder,
  fetchTables,
  fetchHalls,
  updateTableStatus,
  fetchOrderById,
  updateOrderItemStatus,
  toggleProductAvailability,
  updateOrderItem,
  removeOrderItem,
  acceptQROrder,
  rejectQROrder,
} from './head-api';
